as yet unclassified
initialize

	"ChronologyConstants initialize" 	SqueakEpoch _ 2415386. 		"Julian day number of 1 Jan 1901" 

	SecondsInDay _ 86400.

	SecondsInHour _ 3600.

	SecondsInMinute _ 60.

	NanosInSecond _ 10 raisedTo: 9.

	NanosInMillisecond _ 10 raisedTo: 6.

	DayNames _ #(Sunday Monday Tuesday Wednesday Thursday Friday Saturday).

		

	MonthNames _ #(January February March April May June July

 			August September October November December).

	DaysInMonth _ #(31 28 31 30 31 30 31 31 30 31 30 31).