language: erlang

env:
#   - ST=GemStone-2.4.4.1
#   - ST=GemStone-2.4.4.7 
#   - ST=GemStone-2.4.5
#   - ST=GemStone-2.4.5.1
#   - ST=GemStone-3.0.1
   - ST=GemStone-3.1.0.2 CONFIGURATION=GLASS VERSION="1.0-beta.9" REPOSITORY="http://seaside.gemstone.com/ss/MetacelloRepository"

install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -q -O builderCI.zip https://github.com/dalehenrich/builderCI/zipball/master
   - unzip -q builderCI.zip
   - cd dalehenrich-builderCI*
   - source build_env_vars
   - ln -s $PROJECT_HOME $GIT_PATH
   - ./build_image.sh

script: $PROJECT_HOME/tests/testTravisCI.sh -verbose
