GsDevKit Issue 83
setUpGsDevKitIssue83Baz2: ancestors
  "self reset"

  ^ self
    setUpPackageClassDefs:
      {#'Object'.
      #'GsDevKitIssue83A'.
      #(#'ivar').
      #().
      #().
      #'GsDevKitIssue83A'.
      #'GsDevKitIssue83B'.
      #().
      #().
      #().
      #'GsDevKitIssue83B'.
      #'GsDevKitIssue83C'.
      #().
      #().
      #().
      #'GsDevKitIssue83B'.
      #'GsDevKitIssue83D'.
      #().
      #().
      #()}
    methodDefs:
      {'GsDevKitIssue83B'.
      'xxx'.
      'xxx | bvar | bvar := 1. ^bvar'}
    named: 'GsDevKit83Baz-dkh.2'
    ancestors: ancestors