SystemOrganization addCategory: #'Squeak-Collections-Arrayed'!
SystemOrganization addCategory: #'Squeak-Collections-Streams'!
SystemOrganization addCategory: #'Squeak-Collections-Text'!
SystemOrganization addCategory: #'Squeak-Collections-Unordered'!
SystemOrganization addCategory: #'Squeak-Exceptions'!
SystemOrganization addCategory: #'Squeak-Gemstone'!
SystemOrganization addCategory: #'Squeak-Graphics-Primitives'!
SystemOrganization addCategory: #'Squeak-Kernel-Chronology'!
SystemOrganization addCategory: #'Squeak-Kernel-Numbers'!
SystemOrganization addCategory: #'Squeak-Kernel-Objects'!
SystemOrganization addCategory: #'Squeak-Kernel-ST80 Remnants'!
SystemOrganization addCategory: #'Squeak-Network-Url'!
SystemOrganization addCategory: #'Squeak-System-FilePackage'!
SystemOrganization addCategory: #'Squeak-System-Support'!
SystemOrganization addCategory: #'Squeak-Tests'!
SystemOrganization addCategory: #'Squeak-Tools-Browser'!
